# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Frontend Code Quality
on:
  workflow_call: {}
  pull_request:
    branches:
      - main
jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: './package-lock.json'
      - name: Install dependencies
        run: |
          npm install
      - name: Run checks
        run: |
          npm run lint

  unit-ui-testing:
    runs-on: wellsky-gcp-dev
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: './package-lock.json'
      - name: Install dependencies
        run: |
          npm install
      - name: Run checks
        run: |
          npm run test
      - name: Fix paths in lcov.info
        run: sed -i ./coverage/lcov.info -e 's/^SF:/SF:frontend\//'
      - name: Upload code coverage report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          title: Frontend Code Coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./frontend/coverage/lcov.info
